### PR TITLE
Fixed plugin to set syntax to new language format

### PR DESCRIPTION
**Pull request by personalnadir**
Should fix the case of the syntax highlight vanishing on a save

### CODE REVIEW

**Comment by Shchvova** [comment]
@personalnadir Thanks for responding this fast. with your fix it does switch to Corona Lua after the save. Do you know is it possible to make  "Corona Lua" syntax stick, and be default? As I understand if not switching on save, it will just switch to Lua :(
I'm not fan of the method either.
Also, do you know if there's a way to make build.settings file also highlighted?

**Comment by personalnadir** [comment]
It's actually something you can control in Sublime from the UI. Select View -> Syntax -> Open all with current extension as... 

You'll notice it adds the following to the CoronaSDKLua sublime settings:
```
{
	"extensions":
	[
		"lua"
	]
}
```

Adding that to the .sublime-settings file in the repository _might_ make that behaviour the default, though I'm not sure if that's a good idea. 

An alternative would be to try to move the syntax setting from the post_save function in completions to the init. I'm not sure why that isn't done that way as it is.

**Comment by Shchvova** [comment]
Still crashing, if installed from the package manager. Because it installs as an archive, it has no such file (`Corona Editor.sublime-package`).
I commented out code which is crashing. It is better than not doing it. Also tried to insert CoronaSDKLua sublime settings file, but it doesn't seem to work... I have no idea what I am doing ...

**Comment by Shchvova** [comment]
@personalnadir I was getting 
```
Error loading syntax file "Packages/CoronaSDK-SublimeText/CoronaSDKLua.sublime-syntax": Unable to read Packages/CoronaSDK-SublimeText/CoronaSDKLua.sublime-syntax
``
On v1.7.6. I released 1.7.7 since where those lines are commented out. There is a big problem: when you're installing it via custom repo (like instructions in README.md), it all works, because it is installed as source code. But when installed from Package Control:
(Package Control, install Corona Editor) it did fail

**Comment by personalnadir** [comment]
I've created a new pull request to fix this

**Pull request merged**
