### PR TITLE
Possible fix

### LINKED ISSUE #41: Plugin only works on install, crash if sublime is relaunched
When I install the plugin, everything works fine.
If sublime is relaunched, completions doesn't work anymore, and probably other stuffs. This is what the console says:

```
reloading plugin Corona Editor._corona_utils
reloading plugin Corona Editor._lua_paths
reloading plugin Corona Editor._sublime_utils
reloading plugin Corona Editor.about
reloading plugin Corona Editor.completions
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/akabab/Library/Application Support/Sublime Text 3/Installed Packages/Corona Editor.sublime-package/completions.py", line 27, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'User/CoronaSDKLua.sublime-settings'
reloading plugin Corona Editor.corona_docs
reloading plugin Corona Editor.debugger
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/akabab/Library/Application Support/Sublime Text 3/Installed Packages/Corona Editor.sublime-package/debugger.py", line 20, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'User/CoronaSDKLua.sublime-settings'
reloading plugin Corona Editor.run_project
reloading plugin Corona Editor.snippets
Traceback (most recent call last):
  File "/Users/akabab/Library/Application Support/Sublime Text 3/Installed Packages/Corona Editor.sublime-package/snippets.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/akabab/Library/Application Support/Sublime Text 3/Installed Packages/Corona Editor.sublime-package/completions.py", line 27, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'User/CoronaSDKLua.sublime-settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/akabab/Library/Application Support/Sublime Text 3/Installed Packages/Corona Editor.sublime-package/snippets.py", line 21, in <module>
ImportError: No module named 'completions'
```

Any idea? 
Thx u

### PR DESCRIPTION
**Pull request by personalnadir**
I think this might fix #41. It seems to behave okay on my local version

### CODE REVIEW

**Comment by akabab** [comment]
how to get the fix ?

**Comment by personalnadir** [comment]
Upgrade the package in Sublime. Look for the package manager commands in the command palette

Best,

Tom

**Comment by akabab** [comment]
@personalnadir nothing to upgrade, it sticks with v1.7.7
else I found it work if I add the repository to package manager, and install the package CoronaSDK-SublimeText which is the most recent version I suppose

**Comment by akabab** [comment]
Oh well, there is another issue now.. when I save the file, the syntax switch from "Corona Lua" to "CoronaSDKLua" and gives an error popup 
```
Error loading syntax file "Packages/Corona Editor/CoronaSDKLua.sublime-syntax": Unable to read Packages/Corona Editor/CoronaSDKLua.sublime-syntax
```

**Comment by personalnadir** [comment]
This is caused by the fact that when you instal from GitHub directly it installs the package into a different directory based on the repository name. It means that the syntax file is in a different location. I’ve created a pull request to fix this. You can also fix this manually by copying the sublime-syntax file into the Corona Editor directory in you Sublime packages directory.

Tom

**Pull request merged**
