### PR TITLE
Syntax Update and Autocomplete Extras

### PR DESCRIPTION
**Pull request by personalnadir**
I've updated the syntax definitions file to the new YAML format. I've made a change to the function highlighting. It now no longer checks for 'local', which I think makes things easier. 

This version also incorporates some simple string completion. When completing strings for require statements it attempts to add relevant '.lua' files to the autocomplete suggestions.

When completing strings in other contexts, it searches for files with specific extensions. These are controlled using the new "corona_sdk_autocomplete_extensions" option.

The process is not perfect, it works best when a project has been properly configured. However it takes into account any currently open files and looks recursively at their folder and any subfolders within.

### CODE REVIEW

**Comment by sekodev** [comment]
Not sure if it works as expected but it seems there are too many changes here. Any plans to merge this into master branch @Shchvova ?

**Comment by personalnadir** [comment]
This is my standard setup when developing Corona apps. The autocomplete does not fully replace the triggering text if it contains a '/'. So if you type ```display.newImage("img``` and select an image path the autocomplete will replace the ```img```. If you type ```display.newImage("img/"``` the autocomplete will append the text to resulting in ```display.newImage("img/img/example.png"```. From memory I think fixing this was not simple enough for me to attempt it at the time, though I might go back and have a look at it.

**Comment by Shchvova** [comment]
@personalnadir hey. So after merging this PR, it is upstream now, there is an issue that sytax highlight disappears after saving the file (it gets unchecked from "Corona Lua"). Any ideas?

**Comment by personalnadir** [comment]
That’s odd, I had that issue a while ago, but not recently. I’ve just tested the version of Corona Editor using the official repository. I got the following error message pop up:
```Error loading syntax file "Packages/CoronaSDK-SublimeText/CoronaSDKLua.tmLanguage": Unable to open Packages/CoronaSDK-SublimeText/CoronaSDKLua.tmLanguage```

I notice that the project now has both the older .tmLanguage and the newer .sublime-syntax formats. That may be confusing things. I noticed completions.py and debugger.py had some references to the old CoronaSDKLua.tmLanguage files, which I've now removed. 

Can you add my repository and to Package Manager, and install the version directly from there and see if you get the same issues? If it works I'll do another pull request with the python changes and the tmLanguage file removed.

**Comment by personalnadir** [comment]
Interestingly I think that the post save function will set any Lua file to have the Corona SDK syntax, which may not be desirable. I've always wondering if there might be a more granular approach.

**Comment by Shchvova** [comment]
@personalnadir yes, we added old tmLanguage because it was giving error. Now it just resets to have no syntax highlight after the build.

**Comment by personalnadir** [comment]
@Shchvova Does the version from my repository have the same issue? If I use the version of the plugin from my repository I don't see the issue, however I do see it if I use the version from this repository.

**Comment by Shchvova** [comment]
Yes. Just tried, fixed on both of my computers. Please make another PR when possible.

**Comment by personalnadir** [comment]
Have done, let me know if there's anything that needs changing

**Pull request merged**
